---
# tasks file for nvm
# vim: noai:ts=2:sw=2:expandtab
- name: Ensure required packages are present
  apt:
    name: "{{ item }}"
  with_items:
  - build-essential
  - libssl-dev
  become: True

- name: download nvm
  get_url:
    url: "https://raw.githubusercontent.com/creationix/nvm/{{nvm_version}}/install.sh"
    dest: "/home/{{ user_account }}/install.sh"
    owner: "{{ user_account }}"
    group: "{{ user_account }}"
    mode: 0755
  become: True

- name: "install nvm"
  shell: "/home/{{ user_account }}/install.sh"
  args:
    creates: "/home/{{ user_account }}/.nvm"
  become: yes
  become_user: "{{ user_account }}"

- name: "install node"
  shell: "NVM_DIR=/home/{{user_account}}/.nvm && . ${NVM_DIR}/nvm.sh && nvm install {{nvm_node_version}} && nvm use {{nvm_node_version}}"
  args:
    chdir: "/home/{{ user_account }}"
  become: yes
  become_user: "{{ user_account }}"

- name: "install node global libraries"
  shell: "NVM_DIR=/home/{{user_account}}/.nvm && . ${NVM_DIR}/nvm.sh && nvm use {{nvm_node_version}} && npm install -g {{item}}"
  args:
    chdir: "/home/{{ user_account }}"
  with_items: "{{nodejs_npm_global_packages}}"
  become: yes
  become_user: "{{ user_account }}"
