## vim: noai:ts=2:sw=2:expandtab
---
- name: ambiance theme repository
  apt_repository: repo='ppa:ravefinity-project/ppa'
- name: xfwm-theme-manager Repository
  become: True
  apt_repository: repo='ppa:rebuntu16/other-stuff'
- name: additional packages
  apt: name="{{item}}"
  with_items:
    - xubuntu-desktop
    - cairo-dock
    - libreoffice-gtk
    - xfce-theme-manager
    - ambiance-flat-colors
    - ambiance-radiance-xfce-lxde
    - radiance-flat-colors
    - xscreensaver
- name: remove packages
  apt: name="{{item}}" state=absent
  with_items:
    - abiword
    - light-locker
- name: Wallpaper
  get_url: url=https://www.ppload.com/api/files/download?id=1460914629 dest=/usr/share/xfce4/backdrops/100418-3dbuntu3.jpg
- name: xfce4 | configuration | ensure directory
  file: path={{xubuntu_home}}/.config state=directory owner="{{xubuntu_user}}" group="{{xubuntu_user}}"
- name: xfce4 | copy config
  unarchive: src=xfce4-config.tar.gz dest={{xubuntu_home}} owner="{{xubuntu_user}}" group="{{xubuntu_user}}"
#- name: Disable automatic login
#  template: src=custom.conf.j2 dest="/etc/gdm/custom.conf" backup=yes mode=0644
#  tags: configuration
