---
- hosts: localhost
  become: True
  tasks:
  - name: "check preconditions"
    assert:
      that:
      - "user_account is defined"
      - "user_password is defined"
  - name: "create user {{ user_account }}"
    user:
      name: "{{ user_account }}"
      shell: /bin/bash
      password: "{{ user_password }}"
      generate_ssh_key: "{{ user_ssh_key is undefined }}"
      groups: sudo
  - block:
    - name: "create ssh directory"
      file:
        path: "/home/{{ user_account }}/.ssh"
        state: directory
        mode: 0700
        owner: "{{ user_account }}"
        group: "{{ user_account }}"
    - name: "copy pre-defined ssh key"
      copy:
        content: "{{ user_ssh_key }}"
        dest: "/home/{{ user_account }}/.ssh/id_rsa"
        mode: 0600
        owner: "{{ user_account }}"
        group: "{{ user_account }}"
    when: "user_ssh_key is defined"
  vars_files:
  - ../default.yml
  - ../customization.yml
