- name: "ensure Desktop directoy is present"
  file:
    path: "/home/{{ icon_user_account }}/Desktop"
    owner: "{{icon_user_account}}"
    state: directory

- name: "create desktop icon"
  template:
    src: "app.desktop.j2"
    dest: "/home/{{ icon_user_account }}/Desktop/{{ entry.id }}.desktop"
    mode: a+x
    owner: "{{icon_user_account}}"
